source "https://rubygems.org"

gem "a2a-rails", path: "../.."
gem "rails", ENV.fetch("QUEUE_RAILS_VERSION", "~> 8.1.0")
gem "sqlite3", ">= 2.1", "< 3"
gem "solid_queue", "~> 1.2.4"
gem "sidekiq", "~> 7.3"
gem "puma", ">= 6.6", "< 8"
