# frozen_string_literal: true

require "a2a"
require_relative "../test_helper"

class AgentCardBuilderContractTest < Minitest::Test
  Handler = ->(message:, context:) { [message, context] }

  def test_generated_card_is_accepted_by_real_agent2agent_v1_schema
    agent = Class.new(A2A::Rails::Agent)
    agent.name "Contract Agent"
    agent.description "Generated by a2a-rails"
    agent.version "1.0"
    agent.skill :reply,
      description: "Reply to text",
      tags: %w[echo],
      examples: ["Hello"],
      input_modes: ["text/plain"],
      output_modes: ["text/plain"],
      handler: Handler

    card = A2A::Rails::AgentCard::Builder.new(
      agent: agent,
      public_base_url: "https://example.com"
    ).call

    schema = A2A::Protocol::JsonSchema["Agent Card"].new(card)
    assert_same schema, schema.valid!
  end
end
